### ISSUE TITLE
Lofreq issue checklist

### ISSUE THREAD

**Issue by Krannich479** [rki-mf1/omnifluss#25]
I require the following to be fixed in **nf-core**, s.t. lofreq works seamlessly:

- lofreq/viterbi:
- [x] stub
- [x] tests
- [x] normalized input maps

- lofreq/indelqual:
- [x] stub
- [x] tests
- [x] normalized input maps

- lofreq/callparallel:
- [x] stub
- [x] tests
- [x] normalized input maps

---
Closes #19
